version: 0.0.7#{build}
image: Visual Studio 2017
environment:
  matrix:
  - VC_ARCH: x86
    QT_PATH: C:\Qt\5.11.2\msvc2015
    OPENSSL_PATH: C:\OpenSSL-Win32
    INNO_ARGS: ''
    ARTIFACT_SUFFIX: _x86
  - VC_ARCH: amd64
    QT_PATH: C:\Qt\5.11.2\msvc2017_64
    OPENSSL_PATH: C:\OpenSSL-Win64
    INNO_ARGS: /DBUILD64
install:
- ps: >-
    choco install innosetup

    [Environment]::CurrentDirectory = $PWD
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %VC_ARCH%

    SET PATH=%PATH%;%QT_PATH%\bin;"C:\Program Files (x86)\Inno Setup 5"

    qmake OpenRCT2Launcher.pro

    nmake

    mkdir build-Windows

    copy release\OpenRCT2.exe build-Windows\OpenRCT2.exe

    windeployqt build-Windows\OpenRCT2.exe

    copy %OPENSSL_PATH%\libeay32.dll build-Windows\

    copy %OPENSSL_PATH%\ssleay32.dll build-Windows\

    pushd build-Windows & 7z a -tzip ..\OpenRCT2Launcher-win%ARTIFACT_SUFFIX%.zip * & popd

    iscc %INNO_ARGS% installer.iss
artifacts:
- path: OpenRCT2Launcher-win*.zip
  name: zip-archive
- path: OpenRCT2Launcher-win*.exe
  name: exe-installer
deploy:
- provider: GitHub
  auth_token:
    secure: US2B1AJBegrxUhjKUfbocWUqavl636DxnaUnl8a7/waGexpd5Dp/mN6JBZIS+6Ee
  artifact: zip-archive, exe-installer
  on:
    appveyor_repo_tag: true
